field: 57a42f69-564f-4d11-b2e9-8285220eab31
fieldLayouts:
  9d58aae7-3c30-49e1-8aff-a5563dbc6b3a:
    tabs:
      -
        elements:
          -
            fieldUid: b7e1da54-a49e-4209-b56a-becb90315f25
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3dddc70c-404a-4dcf-bf22-f2d8fda2aa34
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 216a5716-d459-4f74-bc80-57e612e4bc9c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  216a5716-d459-4f74-bc80-57e612e4bc9c:
    contentColumnType: text
    fieldGroup: null
    handle: elementparagraph2
    instructions: ''
    name: elementParagraph2
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3dddc70c-404a-4dcf-bf22-f2d8fda2aa34:
    contentColumnType: text
    fieldGroup: null
    handle: elementparagraph1
    instructions: ''
    name: elementParagraph1
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b7e1da54-a49e-4209-b56a-becb90315f25:
    contentColumnType: text
    fieldGroup: null
    handle: elementtitle
    instructions: ''
    name: elementTitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: element
name: element
sortOrder: 1
