field: 1741b25b-a9e6-452a-9bc8-068f511877e2
fieldLayouts:
  dca37def-ec6f-48dc-ad3d-1d59ac0e5a09:
    tabs:
      -
        elements:
          -
            fieldUid: b24d36e9-8a37-41d5-b9d1-6521dc2e0b2d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 88b2ad21-520b-40c8-b4ee-1a555b199bfe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6d088e42-73c2-41aa-bc0f-11f3547c644a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6d088e42-73c2-41aa-bc0f-11f3547c644a:
    contentColumnType: text
    fieldGroup: null
    handle: tableData
    instructions: ''
    name: 'Table Data'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Row Data'
                -
                  - handle
                  - rowData
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - 'Standard Edition'
                -
                  - handle
                  - standardEdition
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - 'Exclusive Edition'
                -
                  - handle
                  - exclusiveEdition
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
            -
              - col3
              - ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  88b2ad21-520b-40c8-b4ee-1a555b199bfe:
    contentColumnType: text
    fieldGroup: null
    handle: matrixSubtitle
    instructions: ''
    name: matrixSubtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b24d36e9-8a37-41d5-b9d1-6521dc2e0b2d:
    contentColumnType: text
    fieldGroup: null
    handle: matrixTitle
    instructions: ''
    name: matrixTitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: element
name: element
sortOrder: 1
