field: 70d771ca-07a3-4890-9fec-cb3cadc49158
fieldLayouts:
  ad543913-a697-4a95-a0f5-af79cbb1953f:
    tabs:
      -
        elements:
          -
            fieldUid: 7c53bcde-78ac-4576-8a50-06f28dfd2431
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 43dee225-a3e4-4faa-8f23-d76ece35e529
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ae8bb340-48e5-44ca-961a-5e4e6d0e0506
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d69e9126-ea8b-4a8b-8b29-290b07c30e50
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  43dee225-a3e4-4faa-8f23-d76ece35e529:
    contentColumnType: text
    fieldGroup: null
    handle: subtitle
    instructions: ''
    name: subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7c53bcde-78ac-4576-8a50-06f28dfd2431:
    contentColumnType: text
    fieldGroup: null
    handle: sectionTitle
    instructions: ''
    name: 'Section Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ae8bb340-48e5-44ca-961a-5e4e6d0e0506:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:0e21ada9-6821-44c5-bc22-69e56704adcb'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:0e21ada9-6821-44c5-bc22-69e56704adcb'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:0e21ada9-6821-44c5-bc22-69e56704adcb'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d69e9126-ea8b-4a8b-8b29-290b07c30e50:
    contentColumnType: text
    fieldGroup: null
    handle: itemsSummary
    instructions: ''
    name: 'Items Summary'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Value
                -
                  - handle
                  - value
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: sectionBlock
name: 'Section block'
sortOrder: 1
