fieldLayouts:
  2f66ebad-f69b-4448-99db-4997826f87f2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: shop
hasUrls: true
name: Shop
settings:
  path: '@webroot/assets/uploads/shop'
sortOrder: 2
type: craft\volumes\Local
url: '@web/assets/uploads/shop'
