contentColumnType: string
fieldGroup: ea7b6f89-efe1-41a4-91f4-b71958991fa3
handle: mainLogoImage
instructions: ''
name: 'Main Logo Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:0e21ada9-6821-44c5-bc22-69e56704adcb'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:0e21ada9-6821-44c5-bc22-69e56704adcb'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:0e21ada9-6821-44c5-bc22-69e56704adcb'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
