contentColumnType: string
fieldGroup: 224285f8-6c4e-4c27-a6d6-0de6b628ee60
handle: otherGames
instructions: ''
name: 'Other Games'
searchable: false
settings:
  contentTable: '{{%matrixcontent_othergames}}'
  maxBlocks: '4'
  minBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
