contentColumnType: text
fieldGroup: f6daf363-3490-4a78-8d3b-75915a9d7d1a
handle: priceTag
instructions: ''
name: 'Price Tag'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
